### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by merelinguist** [soroushchehresa/awesome-coronavirus#84] opened 2020-03-24 10:35 UTC
I understand what you’re going for bud this is not a good look:

<img width="968" alt="Screenshot 2020-03-24 at 10 34 09" src="https://user-images.githubusercontent.com/24858006/77415928-152ffd80-6dbb-11ea-971d-4b8768bb3598.png">

**Comment by soroushchehresa** [comment] 2020-03-24 16:20
Duplicate of #12

**Closed by soroushchehresa** 2020-03-24 16:20 UTC
