### ISSUE TITLE
Remove `Awesome`

### ISSUE THREAD

**Issue by robbiegleeson** [soroushchehresa/awesome-coronavirus#76] opened 2020-03-23 16:23 UTC
Given the significance of this worldwide pandemic I would suggest renaming and removing any words referencing coronavirus as `awesome`. It is in very bad taste - this is a serious issue.

**Comment by soroushchehresa** [comment] 2020-03-23 16:45
Duplicate of #12

**Closed** 2020-03-23 16:45 UTC
